### ISSUE TITLE
MacOS build error: could not find native static library `portaudio`

### ISSUE THREAD

**Issue by eliheuer** [RamiHg/RustyBoy#1]
On MacOS 10.14 with rustc 1.36.0-nightly I try:
```
cargo run --release -- path_to_rom.gb
```
But get the following error:
```
error: could not find native static library `portaudio`, perhaps an -L flag is missing?
```
Tried the `-L` flag in a few different ways but still get the issue.

**Comment by RamiHg** [comment]
Hey,

I've been working over the last week or so to remove the dependency on PortAudio. I've rewritten the audio backend to work with a lower-level library that should link statically. 

It should be building for you now.

**Comment by eliheuer** [comment]
Just pulled from master and it works now, thank you! Great project!
